"""Regenerate workflows/live.yml: N back-to-back ~6 h stints (GitHub caps a job at 6 h and a
workflow run at 35 days). Usage: python .github/gen_live_workflow.py [N]"""
import os
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 100
BRANCH = "claude/wonderful-cannon-ek18kx"
out = [f"""# Live Polymarket BTC estimator: {N} chained ~6 h stints (~{N // 4} days). Generated by
# .github/gen_live_workflow.py. Starts on pushes that change the code/models on this branch;
# stop it by cancelling the run in the Actions tab; restart with "Re-run all jobs".
name: live
on:
  push:
    branches: [{BRANCH}]
    paths: ["live.py", "btcpred/**", "models/**", ".github/**"]
  workflow_dispatch:

concurrency:
  group: live
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  s001:
    uses: ./.github/workflows/live-chunk.yml
"""]
for i in range(2, N + 1):
    out.append(f"""  s{i:03d}:
    needs: s{i - 1:03d}
    if: ${{{{ !cancelled() }}}}
    uses: ./.github/workflows/live-chunk.yml
""")
open(os.path.join(os.path.dirname(__file__), "workflows", "live.yml"), "w").write("".join(out))
